version: '3.8'

services:
  nginx-uoc-based:
    image: nginx-uoc
    networks:
      - docker-rednueva
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 1G
networks:
  docker-rednueva:
    driver: bridge
